import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="text-center p-10 bg-red-50">Header</nav>
        <div className="p-10">
          {children}
        </div>
        <footer className="text-center p-10 bg-red-50">Footer</footer>
      </body>
    </html>
  );
}
